### ISSUE TITLE
Cannot call method 'getCollection' of undefined (docpad v6.70.1)

### ISSUE THREAD

**Issue by przezor** [brockfanning/docpad-plugin-lunr#10]
Hi. 
Plugin does not work with the newest version of docpad - v6.70.1. The error is: 

```
error: Something went wrong with the action
error: An error occured: 
TypeError: Cannot call method 'getCollection' of undefined
  at _indexDocument (/docpad/node_modules/docpad-plugin-lunr/out/lunr.plugin.js:36:36)
  at /docpad/node_modules/docpad-plugin-lunr/out/lunr.plugin.js:49:17
  at Array.forEach (native)
  at LunrPlugin.writeAfter (/docpad/node_modules/docpad-plugin-lunr/out/lunr.plugin.js:48:32)
  at ambi (docpad/node_modules/docpad/node_modules/ambi/out/lib/ambi.js:57:27)
  at Task.<anonymous> (docpad/node_modules/docpad/node_modules/event-emitter-grouped/out/lib/event-emitter-grouped.js:45:23)
  at ambi (docpad/node_modules/docpad/node_modules/ambi/out/lib/ambi.js:55:18)
  at fireMethod (docpad/node_modules/docpad/node_modules/taskgroup/out/lib/taskgroup.js:383:23)
  at b (domain.js:183:18)
  at Domain.run (domain.js:123:23)
  at Task.fire (docpad/node_modules/docpad/node_modules/taskgroup/out/lib/taskgroup.js:421:27)
  at Object._onImmediate (docpad/node_modules/docpad/node_modules/taskgroup/out/lib/taskgroup.js:438:26)
  at processImmediate [as _immediateCallback] (timers.js:336:15)
error: To report the above error, follow the guide at: http://docpad.org/bug-report
```

**Comment by semencov** [comment]
Looks like `out` version of plugin is different from the `src`. I've compiled the coffee source and replaced the `lunr.plugin.js` and it works like a charm.

**Comment by przezor** [comment]
Thanks :)
